#include "swiot_logging_categories.h"

#ifndef QT_NO_DEBUG_OUTPUT
Q_LOGGING_CATEGORY(CAT_SWIOT, "SWIOTPlugin");
Q_LOGGING_CATEGORY(CAT_SWIOT_AD74413R, "AD74413R")
Q_LOGGING_CATEGORY(CAT_SWIOT_CONFIG, "SWIOTConfig")
Q_LOGGING_CATEGORY(CAT_SWIOT_FAULTS, "SWIOTFaults")
Q_LOGGING_CATEGORY(CAT_SWIOT_MAX14906, "MAX14906")
#endif
