
#ifndef SCOPYBAREMINIMUMPLUGIN_EXPORT_H
#define SCOPYBAREMINIMUMPLUGIN_EXPORT_H

#ifdef SCOPYBAREMINIMUMPLUGIN_STATIC_DEFINE
#  define SCOPYBAREMINIMUMPLUGIN_EXPORT
#  define SCOPYBAREMINIMUMPLUGIN_NO_EXPORT
#else
#  ifndef SCOPYBAREMINIMUMPLUGIN_EXPORT
#    ifdef scopybareminimumplugin_EXPORTS
        /* We are building this library */
#      define SCOPYBAREMINIMUMPLUGIN_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SCOPYBAREMINIMUMPLUGIN_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SCOPYBAREMINIMUMPLUGIN_NO_EXPORT
#    define SCOPYBAREMINIMUMPLUGIN_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SCOPYBAREMINIMUMPLUGIN_DEPRECATED
#  define SCOPYBAREMINIMUMPLUGIN_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SCOPYBAREMINIMUMPLUGIN_DEPRECATED_EXPORT
#  define SCOPYBAREMINIMUMPLUGIN_DEPRECATED_EXPORT SCOPYBAREMINIMUMPLUGIN_EXPORT SCOPYBAREMINIMUMPLUGIN_DEPRECATED
#endif

#ifndef SCOPYBAREMINIMUMPLUGIN_DEPRECATED_NO_EXPORT
#  define SCOPYBAREMINIMUMPLUGIN_DEPRECATED_NO_EXPORT SCOPYBAREMINIMUMPLUGIN_NO_EXPORT SCOPYBAREMINIMUMPLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SCOPYBAREMINIMUMPLUGIN_NO_DEPRECATED
#    define SCOPYBAREMINIMUMPLUGIN_NO_DEPRECATED
#  endif
#endif

#endif /* SCOPYBAREMINIMUMPLUGIN_EXPORT_H */
