
#ifndef SCOPY_BAREMINIMUMPLUGIN_EXPORT_H
#define SCOPY_BAREMINIMUMPLUGIN_EXPORT_H

#ifdef SCOPY_BAREMINIMUMPLUGIN_STATIC_DEFINE
#  define SCOPY_BAREMINIMUMPLUGIN_EXPORT
#  define SCOPY_BAREMINIMUMPLUGIN_NO_EXPORT
#else
#  ifndef SCOPY_BAREMINIMUMPLUGIN_EXPORT
#    ifdef scopy_bareminimumplugin_EXPORTS
        /* We are building this library */
#      define SCOPY_BAREMINIMUMPLUGIN_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SCOPY_BAREMINIMUMPLUGIN_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SCOPY_BAREMINIMUMPLUGIN_NO_EXPORT
#    define SCOPY_BAREMINIMUMPLUGIN_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SCOPY_BAREMINIMUMPLUGIN_DEPRECATED
#  define SCOPY_BAREMINIMUMPLUGIN_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SCOPY_BAREMINIMUMPLUGIN_DEPRECATED_EXPORT
#  define SCOPY_BAREMINIMUMPLUGIN_DEPRECATED_EXPORT SCOPY_BAREMINIMUMPLUGIN_EXPORT SCOPY_BAREMINIMUMPLUGIN_DEPRECATED
#endif

#ifndef SCOPY_BAREMINIMUMPLUGIN_DEPRECATED_NO_EXPORT
#  define SCOPY_BAREMINIMUMPLUGIN_DEPRECATED_NO_EXPORT SCOPY_BAREMINIMUMPLUGIN_NO_EXPORT SCOPY_BAREMINIMUMPLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SCOPY_BAREMINIMUMPLUGIN_NO_DEPRECATED
#    define SCOPY_BAREMINIMUMPLUGIN_NO_DEPRECATED
#  endif
#endif

#endif /* SCOPY_BAREMINIMUMPLUGIN_EXPORT_H */
