
#ifndef SCOPY_AD6676PLUGIN_EXPORT_H
#define SCOPY_AD6676PLUGIN_EXPORT_H

#ifdef SCOPY_AD6676PLUGIN_STATIC_DEFINE
#  define SCOPY_AD6676PLUGIN_EXPORT
#  define SCOPY_AD6676PLUGIN_NO_EXPORT
#else
#  ifndef SCOPY_AD6676PLUGIN_EXPORT
#    ifdef scopy_ad6676plugin_EXPORTS
        /* We are building this library */
#      define SCOPY_AD6676PLUGIN_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SCOPY_AD6676PLUGIN_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SCOPY_AD6676PLUGIN_NO_EXPORT
#    define SCOPY_AD6676PLUGIN_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SCOPY_AD6676PLUGIN_DEPRECATED
#  define SCOPY_AD6676PLUGIN_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SCOPY_AD6676PLUGIN_DEPRECATED_EXPORT
#  define SCOPY_AD6676PLUGIN_DEPRECATED_EXPORT SCOPY_AD6676PLUGIN_EXPORT SCOPY_AD6676PLUGIN_DEPRECATED
#endif

#ifndef SCOPY_AD6676PLUGIN_DEPRECATED_NO_EXPORT
#  define SCOPY_AD6676PLUGIN_DEPRECATED_NO_EXPORT SCOPY_AD6676PLUGIN_NO_EXPORT SCOPY_AD6676PLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SCOPY_AD6676PLUGIN_NO_DEPRECATED
#    define SCOPY_AD6676PLUGIN_NO_DEPRECATED
#  endif
#endif

#endif /* SCOPY_AD6676PLUGIN_EXPORT_H */
