
#ifndef SCOPY_DEBUGGERPLUGIN_EXPORT_H
#define SCOPY_DEBUGGERPLUGIN_EXPORT_H

#ifdef SCOPY_DEBUGGERPLUGIN_STATIC_DEFINE
#  define SCOPY_DEBUGGERPLUGIN_EXPORT
#  define SCOPY_DEBUGGERPLUGIN_NO_EXPORT
#else
#  ifndef SCOPY_DEBUGGERPLUGIN_EXPORT
#    ifdef scopy_debuggerplugin_EXPORTS
        /* We are building this library */
#      define SCOPY_DEBUGGERPLUGIN_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SCOPY_DEBUGGERPLUGIN_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SCOPY_DEBUGGERPLUGIN_NO_EXPORT
#    define SCOPY_DEBUGGERPLUGIN_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SCOPY_DEBUGGERPLUGIN_DEPRECATED
#  define SCOPY_DEBUGGERPLUGIN_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SCOPY_DEBUGGERPLUGIN_DEPRECATED_EXPORT
#  define SCOPY_DEBUGGERPLUGIN_DEPRECATED_EXPORT SCOPY_DEBUGGERPLUGIN_EXPORT SCOPY_DEBUGGERPLUGIN_DEPRECATED
#endif

#ifndef SCOPY_DEBUGGERPLUGIN_DEPRECATED_NO_EXPORT
#  define SCOPY_DEBUGGERPLUGIN_DEPRECATED_NO_EXPORT SCOPY_DEBUGGERPLUGIN_NO_EXPORT SCOPY_DEBUGGERPLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SCOPY_DEBUGGERPLUGIN_NO_DEPRECATED
#    define SCOPY_DEBUGGERPLUGIN_NO_DEPRECATED
#  endif
#endif

#endif /* SCOPY_DEBUGGERPLUGIN_EXPORT_H */
