
#ifndef SCOPY_DATAMONITORPLUGIN_EXPORT_H
#define SCOPY_DATAMONITORPLUGIN_EXPORT_H

#ifdef SCOPY_DATAMONITORPLUGIN_STATIC_DEFINE
#define SCOPY_DATAMONITORPLUGIN_EXPORT
#define SCOPY_DATAMONITORPLUGIN_NO_EXPORT
#else
#ifndef SCOPY_DATAMONITORPLUGIN_EXPORT
#ifdef scopy_datamonitorplugin_EXPORTS
/* We are building this library */
#define SCOPY_DATAMONITORPLUGIN_EXPORT __attribute__((visibility("default")))
#else
/* We are using this library */
#define SCOPY_DATAMONITORPLUGIN_EXPORT __attribute__((visibility("default")))
#endif
#endif

#ifndef SCOPY_DATAMONITORPLUGIN_NO_EXPORT
#define SCOPY_DATAMONITORPLUGIN_NO_EXPORT __attribute__((visibility("hidden")))
#endif
#endif

#ifndef SCOPY_DATAMONITORPLUGIN_DEPRECATED
#define SCOPY_DATAMONITORPLUGIN_DEPRECATED __attribute__((__deprecated__))
#endif

#ifndef SCOPY_DATAMONITORPLUGIN_DEPRECATED_EXPORT
#define SCOPY_DATAMONITORPLUGIN_DEPRECATED_EXPORT SCOPY_DATAMONITORPLUGIN_EXPORT SCOPY_DATAMONITORPLUGIN_DEPRECATED
#endif

#ifndef SCOPY_DATAMONITORPLUGIN_DEPRECATED_NO_EXPORT
#define SCOPY_DATAMONITORPLUGIN_DEPRECATED_NO_EXPORT                                                                   \
	SCOPY_DATAMONITORPLUGIN_NO_EXPORT SCOPY_DATAMONITORPLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#ifndef SCOPY_DATAMONITORPLUGIN_NO_DEPRECATED
#define SCOPY_DATAMONITORPLUGIN_NO_DEPRECATED
#endif
#endif

#endif /* SCOPY_DATAMONITORPLUGIN_EXPORT_H */
