#ifndef CONFIG_H_CMAKEIN
#define CONFIG_H_CMAKEIN

#define PROJECT_VERSION ""
#define SCOPY_VERSION_GIT "ae0feca0"
#define BREAKPAD_HANDLER 0
#define PYTHON_VERSION "python."

#endif // CONFIG_H_CMAKEIN
