#ifndef SCOPY_PLUGINBASE_CONFIG_H_CMAKEIN
#define SCOPY_PLUGINBASE_CONFIG_H_CMAKEIN

#define SCOPY_VERSION "2.0.0"
#define SCOPY_VERSION_GIT "ddb51f65"
#define SCOPY_GIT_DIRTY "dirty"

#define ENABLE_SCOPYJS

#endif // SCOPY_PLUGINBASE_CONFIG_H_CMAKEIN

