#!/bin/bash

echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
echo REPO_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
echo BUILD_HOST=${BUILD_HOST}
echo USERNAME=${USERNAME}
echo GITHUB_SERVER_URL=${GITHUB_SERVER_URL}
echo GITHUB_API_URL=${GITHUB_API_URL}
echo GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY%/*}
echo GITHUB_REPOSITORY=${GITHUB_REPOSITORY#*/}
echo GITHUB_RUN_ID=${GITHUB_RUN_ID}
echo GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
echo GITHUB_JOB=${GITHUB_JOB}
echo GITHUB_RUN_ID=${GITHUB_RUN_ID}
echo GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
echo RUNNER_ARCH=${RUNNER_ARCH}