#!/bin/bash

STAGING_AREA=$PWD/staging
STAGING_AREA_DEPS=$STAGING_AREA/dependencies
REPO_SRC=$(git rev-parse --show-toplevel)
BUILDDIR=$REPO_SRC/build
JOBS=-j8
QT_FORMULAE=qt@5
QT_PATH="$(brew --prefix ${QT_FORMULAE})/bin"
export PATH="${QT_PATH}:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH;$STAGING_AREA_DEPS;$STAGING_AREA_DEPS/lib"


LIBIIO_VERSION=v0.25
LIBAD9361_BRANCH=main
LIBM2K_BRANCH=main
GNURADIO_BRANCH=scopy2-maint-3.10
GRSCOPY_BRANCH=3.10
GRM2K_BRANCH=main
QWT_BRANCH=qwt-multiaxes
LIBSIGROKDECODE_BRANCH=master
LIBTINYIIOD_BRANCH=master
