#!/bin/bash

STAGING_AREA=$PWD/staging
STAGING_AREA_DEPS=$STAGING_AREA/dependencies
REPO_SRC=$(git rev-parse --show-toplevel)
BUILDDIR=$REPO_SRC/build
JOBS=-j8

# Qt6 via aqtinstall (clang_64 universal binary)
QT_INSTALL_LOCATION=$HOME/Qt
QT=$QT_INSTALL_LOCATION/6.8.3/macos
QT_PATH=$QT/bin
QMAKE_BIN=$QT_PATH/qmake6

export PATH="${QT_PATH}:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH;$STAGING_AREA_DEPS;$STAGING_AREA_DEPS/lib"

LIBSERIALPORT_BRANCH=master
LIBIIO_VERSION=v0.26
LIBAD9361_BRANCH=main
LIBAD9166_BRANCH=libad9166-iio-v0
QWT_BRANCH=qwt-multiaxes-updated
LIBTINYIIOD_BRANCH=master
KDDOCK_BRANCH=2.2
ECM_BRANCH=v6.8.0
KARCHIVE_BRANCH=v6.8.0
GENALYZER_BRANCH=main
