# Package metadata
PACKAGE=scopy
ARCHITECTURE=armhf
DEPENDS="libfuse2t64, libxcb-icccm4, libxcb-image0, libxcb-keysyms1, libxcb-render-util0, libxcb-xinerama0, libxkbcommon-x11-0, libxcb-xkb1"
MAINTAINER="Adrian Suciu <adrian.suciu@analog.com>"
HOMEPAGE="https://github.com/analogdevicesinc/scopy"
DESCRIPTION="Scopy for 32-bit architecture"
LONG_DESCRIPTION="This package contains the Scopy software oscilloscope and signal analysis toolset from Analog Devices for 32-bit architecture."
