#ifndef SCOPY_FMCOMMS11_CONFIG_H_CMAKEIN
#define SCOPY_FMCOMMS11_CONFIG_H_CMAKEIN

#define FMCOMMS11_PLUGIN_NAME "Fmcomms11Plugin"
#define FMCOMMS11_PLUGIN_DISPLAY_NAME "FMCOMMS11"
#define FMCOMMS11_PLUGIN_SCOPY_MODULE "fmcomms11"
#define FMCOMMS11_PLUGIN_DESCRIPTION "This is a plugin for FMCOMMS11"

#define ENABLE_SCOPYJS

#endif // SCOPY_FMCOMMS11_CONFIG_H_CMAKEIN
