
install(
	TARGETS ${PROJECT_NAME}
	RUNTIME DESTINATION ${SCOPY_PACKAGE_INSTALL_PATH}/${SCOPY_PARENT_MODULE}/plugins
	LIBRARY DESTINATION ${SCOPY_PACKAGE_INSTALL_PATH}/${SCOPY_PARENT_MODULE}/plugins
	ARCHIVE DESTINATION ${SCOPY_PACKAGE_INSTALL_PATH}/${SCOPY_PARENT_MODULE}/plugins
)

install(FILES ${SCOPY_PACKAGE_BUILD_PATH}/${SCOPY_PARENT_MODULE}/plugins/${SCOPY_MODULE}/res/resources.qrc.depends
	DESTINATION ${SCOPY_PACKAGE_INSTALL_PATH}/${SCOPY_PARENT_MODULE}/plugins/${SCOPY_MODULE}/res)


function(add_plugin_resources directory)
	install(DIRECTORY ${directory} DESTINATION ${SCOPY_PACKAGE_INSTALL_PATH}/${SCOPY_PARENT_MODULE}/resources)
endfunction()