#include "logging_categories.h"

#ifndef QT_NO_DEBUG_OUTPUT
Q_LOGGING_CATEGORY(CAT_TOOL_LAUNCHER, "toolLauncher")
Q_LOGGING_CATEGORY(CAT_OSCILLOSCOPE, "oscilloscope")
Q_LOGGING_CATEGORY(CAT_SIGNAL_GENERATOR, "signalGenerator")
Q_LOGGING_CATEGORY(CAT_VOLTMETER, "voltmeter")
Q_LOGGING_CATEGORY(CAT_POWER_CONTROLLER, "powerController")
Q_LOGGING_CATEGORY(CAT_SPECTRUM_ANALYZER, "spectrumAnalyzer")
Q_LOGGING_CATEGORY(CAT_NETWORK_ANALYZER, "networkAnalyzer")
Q_LOGGING_CATEGORY(CAT_DIGITAL_IO, "digitalIO")
Q_LOGGING_CATEGORY(CAT_LOGIC_ANALYZER, "logicAnalyzer")
Q_LOGGING_CATEGORY(CAT_PATTERN_GENERATOR, "patternGenerator")
Q_LOGGING_CATEGORY(CAT_CALIBRATION, "calibration")
Q_LOGGING_CATEGORY(CAT_CALIBRATION_MANUAL, "calibration.manual")
Q_LOGGING_CATEGORY(CAT_IIO_MANAGER, "iioManager")
#endif
