
#ifndef SCOPY_SWIOTREFACTOR_EXPORT_H
#define SCOPY_SWIOTREFACTOR_EXPORT_H

#ifdef SCOPY_SWIOTREFACTOR_STATIC_DEFINE
#  define SCOPY_SWIOTREFACTOR_EXPORT
#  define SCOPY_SWIOTREFACTOR_NO_EXPORT
#else
#  ifndef SCOPY_SWIOTREFACTOR_EXPORT
#    ifdef scopy_swiotrefactor_EXPORTS
        /* We are building this library */
#      define SCOPY_SWIOTREFACTOR_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SCOPY_SWIOTREFACTOR_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SCOPY_SWIOTREFACTOR_NO_EXPORT
#    define SCOPY_SWIOTREFACTOR_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SCOPY_SWIOTREFACTOR_DEPRECATED
#  define SCOPY_SWIOTREFACTOR_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SCOPY_SWIOTREFACTOR_DEPRECATED_EXPORT
#  define SCOPY_SWIOTREFACTOR_DEPRECATED_EXPORT SCOPY_SWIOTREFACTOR_EXPORT SCOPY_SWIOTREFACTOR_DEPRECATED
#endif

#ifndef SCOPY_SWIOTREFACTOR_DEPRECATED_NO_EXPORT
#  define SCOPY_SWIOTREFACTOR_DEPRECATED_NO_EXPORT SCOPY_SWIOTREFACTOR_NO_EXPORT SCOPY_SWIOTREFACTOR_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SCOPY_SWIOTREFACTOR_NO_DEPRECATED
#    define SCOPY_SWIOTREFACTOR_NO_DEPRECATED
#  endif
#endif

#endif /* SCOPY_SWIOTREFACTOR_EXPORT_H */
