name: Scopy arm64 AppImage Build

on: [push, pull_request]

env:
  BUILD_HOST: ubuntu-20.04
  USERNAME: github-actions

jobs:

  build_scopy_arm64_appimage:
    runs-on: ubuntu-20.04

    steps:
        - uses: actions/checkout@v4
          with:
                set-safe-directory: 'true'
                fetch-depth: '0'

        - name: Pull the Docker Image
          run: docker pull cristianbindea/scopy2-arm64-appimage:latest

        - name: Create Scopy AppImage
          shell: bash
          run: |
                cd $GITHUB_WORKSPACE
                sudo apt update
                ./ci/arm/create_sysroot.sh arm64  install_packages install_qemu
                ./ci/arm/arm_build_process.sh arm64 generate_ci_envs

                docker run \
                        --mount type=bind,source="$GITHUB_WORKSPACE",target=/home/runner/scopy \
                        --env-file $GITHUB_WORKSPACE/ci/general/gh-actions.envs \
                        cristianbindea/scopy2-arm64-appimage:latest \
                        /bin/bash -c    'cd $HOME && \
                                        sudo chown -R runner:runner scopy && \
                                        cd $HOME/scopy && \
                                        ./ci/arm/arm_build_process.sh arm64 install_packages move_tools move_sysroot build_scopy build_iio-emu create_appdir create_appimage move_appimage
                                        '
        - name: Set short git commit SHA
          shell: bash
          run: echo "commit_sha=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_ENV"

        - uses: actions/upload-artifact@v4
          with:
            name: scopy-linux-arm64-${{ env.commit_sha }}
            path: ${{ github.workspace }}/Scopy-arm64.AppImage
