name: Ubuntu 20 Scopy Build

on: [push, pull_request]

env:
  BUILD_HOST: ubuntu-20.04
  USERNAME: github-actions

jobs:

  build_scopy_on_ubuntu20:
    runs-on: ubuntu-20.04
    container:
        image: cristianbindea/scopy2-ubuntu20:latest
        options: --user root
    steps:
        - uses: actions/checkout@v3
        - name: Build Scopy
          run: /bin/bash -c "source $GITHUB_WORKSPACE/ci/ubuntu/install_ubuntu_20_deps.sh && build_scopy"