name: Ubuntu 20 Scopy Build

on: [push, pull_request]

env:
  BUILD_HOST: ubuntu-22.04
  USERNAME: github-actions

jobs:
  docker_tag_workflow:
    uses: ./.github/workflows/get_docker_tag.yml

  build_scopy_on_ubuntu20:
    runs-on: ubuntu-22.04
    needs: docker_tag_workflow
    container:
        image: cristianbindea/scopy2-ubuntu20:${{ needs.docker_tag_workflow.outputs.docker_tag }}
        options: --user root
    steps:
        - uses: actions/checkout@v4
        - name: Build Scopy
          run: |
            /bin/bash -c "git config --global --add safe.directory $GITHUB_WORKSPACE"
            /bin/bash -c "export CI_SCRIPT=ON && $GITHUB_WORKSPACE/ci/ubuntu/ubuntu_build_process.sh build_scopy"