name: Ubuntu 20 Scopy Build

on: [push, pull_request]

env:
  BUILD_HOST: ubuntu-20.04
  USERNAME: github-actions

jobs:

  build_scopy_on_ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Run Build Script
      run: $GITHUB_WORKSPACE/ci/ubuntu/install_ubuntu_20_deps.sh